version: "3.7"
services:
  php:
    build:
      context: docker/php
      target: ${ENVIRONMENT:-production}
    working_dir: /app
    volumes:
      - app:/app:delegated
      - ./docker/php/.bashrc:/root/.bashrc

  nginx:
    build:
      context: docker/nginx
      target: ${ENVIRONMENT:-production}
    working_dir: /app
    ports:
      - ${PORT_HTTP:-8080}:80
    volumes:
      - app:/app:delegated
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    build:
      context: docker/mysql
      target: ${ENVIRONMENT:-production}
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: pass
      TZ: Asia/Tokyo
    working_dir: /app
    volumes:
      - app:/app:delegated
      - mysql:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d

volumes:
  mysql:
  app:
    driver_opts:
      type: none
      device: "${PROJECT_DIR}"
      o: bind
