version: "3.7"
services:
  php:
    build:
      context: docker/php
      target: production
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php/.bashrc:/root/.bashrc

  nginx:
    build:
      context: docker/nginx
      target: production
    working_dir: /app
    ports:
      - ${PORT_HTTP:-8080}:80
    volumes:
      - .:/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
