version: "3.7"
services:
  php:
    build:
      context: docker/php
      target: ${ENVIRONMENT:-production}
    working_dir: /app
    volumes:
      - app:/app:delegated
      - ./docker/php/.bashrc:/root/.bashrc

  nginx:
    build:
      context: docker/nginx
      target: ${ENVIRONMENT:-production}
    working_dir: /app
    ports:
      - ${PORT_HTTP:-8080}:80
    volumes:
      - app:/app:delegated
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  app:
    driver_opts:
      type: none
      device: "${PROJECT_DIR}"
      o: bind
