version: "3.7"
services:
  php:
    build:
      context: docker/symfony
      target: production
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/symfony/.bashrc:/root/.bashrc

  nginx:
    build:
      context: docker/nginx
      target: production
    working_dir: /app
    ports:
      - ${PORT_HTTP:-8080}:80
    volumes:
      - .:/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
